name: 'medical_warehouse'
version: '1.0'
config-version: 2

profile: 'medical_warehouse'  # must match your profiles.yml

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  medical_warehouse:
    staging:
      materialized: view
    marts:
      materialized: table
