medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 127.0.0.1
      user: postgres
      password: postgres
      port: 5433
      dbname: medical_db
      schema: raw
      threads: 1
      keepalives_idle: 0
